Document: keyboard-color-switcher
Title: Debian keyboard-color-switcher Manual
Author: <insert document author here>
Abstract: This manual describes what keyboard-color-switcher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keyboard-color-switcher/keyboard-color-switcher.sgml.gz

Format: postscript
Files: /usr/share/doc/keyboard-color-switcher/keyboard-color-switcher.ps.gz

Format: text
Files: /usr/share/doc/keyboard-color-switcher/keyboard-color-switcher.text.gz

Format: HTML
Index: /usr/share/doc/keyboard-color-switcher/html/index.html
Files: /usr/share/doc/keyboard-color-switcher/html/*.html
